#! /bin/bash

# Copyright (C) 2015 Ross Burton <ross@burtonini.com>
# MIT licensed

set -e

BLACKLIST=$(git config --get rebase-all.blacklist) || true
# Always blacklist master
BLACKLIST="$BLACKLIST master"

# Returns error if blacklisted
check_blacklisted() {
    NAME=$1
    for BL in $BLACKLIST; do
        if [ "$NAME" = "$BL" ]; then
            echo $NAME is blacklisted
            return 1
        fi
    done
    return 0
}

# Get upstream branch name
get_upstream() {
    NAME=$1
    UPSTREAM=$(git config --get branch.$1.upstream ) || UPSTREAM="origin/master"
    echo $UPSTREAM
}

COUNT=0
FAILED=0

BRANCHES=$(git for-each-ref refs/heads --format='%(refname:strip=2)')
for NAME in $BRANCHES; do
    COUNT=$((COUNT + 1))
 
    check_blacklisted $NAME || continue

    git checkout --quiet $NAME || continue
    if ! git try-rebase $(get_upstream $NAME); then
        FAILED=$((FAILED + 1))
    fi
done

git checkout --quiet master

echo
echo "Rebased $COUNT branches, $FAILED didn't rebase successfully."
