#! /bin/sh

# Copyright (C) 2015 Ross Burton <ross@burtonini.com>
# MIT licensed

if [ $# -ne 1 ]; then
    echo "git try-rebase [UPSTREAM]"
    exit 1
fi

UPSTREAM="$1"

NAME=$(git symbolic-ref HEAD)
NAME=${NAME##refs/heads/}

BOLD=`tput bold`
NORMAL=`tput sgr0`

git rebase "$1" >/dev/null 2>/dev/null
if [ $? -eq 0 ]; then
   echo $NAME rebased to $UPSTREAM
   exit 0
else
   git rebase --abort
   echo ${BOLD}$NAME failed to rebase to $UPSTREAM${NORMAL}
   exit 1
fi
